'use client'

import Link from 'next/link'
import { useState, type FormEvent, type ReactNode } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { ArrowDown, ArrowUpRight, Plus } from 'lucide-react'
import { capabilities, processSteps, services } from '@/content/site'
import { buildContactMailto } from '@/lib/contact'
import { MagneticLink, RegistryHoverButton, Reveal, ScrollStory, ScrollWord, StaggeredHeadline } from './motion'

export function PageIntro({ kicker, title, accent, children }: { kicker: string; title: string; accent: string; children: ReactNode }) { return <section className="page-intro wrap"><Reveal><p className="eyebrow"><span className="pulse" />{kicker}</p><h1><StaggeredHeadline lines={[title, <em key="accent">{accent}</em>]} /></h1><p className="lede">{children}</p></Reveal></section> }

function HeroVisual() { const reduced = useReducedMotion() ?? true; return <motion.div className="hero-visual" initial={reduced ? { opacity: 1 } : { opacity: 0, scale: .98 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: reduced ? 0 : .8 }} aria-label="Abstract composition showing a focused system becoming a clear interface"><span className="visual-label top">DERRICODE / STUDIO</span><span className="visual-label bottom">CONTEXT / OUTCOME</span><span className="visual-line" /><span className="visual-line right" /><span className="visual-ring" /><span className="visual-core" /></motion.div> }

export function ServiceList() { return <div className="service-list">{services.map((service, i) => <Reveal key={service.number} delay={i * .08}><article className="service-row"><span className="service-number">{service.number}</span><div className="service-title"><h3>{service.title}</h3><p>{service.summary}</p></div><p className="service-detail">{service.detail}</p></article></Reveal>)}</div> }

export function Cta() { return <section className="contact wrap section"><div className="contact-card"><div><div className="section-kicker">A considered next step</div><h2>Start with the<br /><em>real question.</em></h2><p>Tell us what you are trying to improve, automate, or build. We will reply with a practical way to begin.</p><Link className="button button-light" href="/contact"><RegistryHoverButton>Talk to Derricode <ArrowUpRight aria-hidden="true" size={16} /></RegistryHoverButton></Link></div><div className="contact-mark" aria-hidden="true">D<span>/</span></div></div></section> }

export function HomePage() { return <><section className="hero wrap"><div className="hero-copy"><Reveal><p className="eyebrow"><span className="pulse" />AI implementation & software studio</p><h1><StaggeredHeadline lines={['Make the next', <em key="accent">useful thing.</em>]} /></h1><p className="lede">Derricode helps businesses turn complex opportunities into clear, working systems—through AI implementation, thoughtful automation, and software built around the way people actually work.</p><div className="hero-actions"><Link className="button button-blue" href="/contact"><MagneticLink>Talk through an opportunity <ArrowUpRight aria-hidden="true" size={16} /></MagneticLink></Link><Link className="text-link" href="/services">Explore the practice <ArrowDown aria-hidden="true" size={16} /></Link></div></Reveal></div><HeroVisual /></section><section className="signal-strip" aria-label="Derricode focus areas"><div className="wrap signal-inner"><span>AI implementation</span><Plus aria-hidden="true" size={14} /><span>Workflow systems</span><Plus aria-hidden="true" size={14} /><span>Web & mobile products</span><Plus aria-hidden="true" size={14} /><span>APIs & MCP integrations</span></div></section><section className="scroll-statement section"><div className="wrap"><div className="section-kicker">A useful distinction</div><h2><ScrollWord text="Context before complexity." /></h2></div></section><section className="section"><div className="wrap split"><Reveal><div className="section-kicker">01 — Point of view</div><h2>Technology earns its place when it makes <em>good work easier.</em></h2></Reveal><Reveal delay={.1} direction="right"><p className="big-copy">The hard part is rarely the tool. It is understanding the decision, the workflow, and the people around it.</p><p>We work from that context outward, connecting business intent to implementation without turning the work into a science project.</p></Reveal></div></section><section className="dark-section section"><div className="wrap split"><Reveal><div className="section-kicker">02 — Our practice</div><h2>Clarity first.<br /><em>Then momentum.</em></h2></Reveal><Reveal delay={.1}><p className="big-copy">A good system should feel considered from the first interaction—and remain understandable after it ships.</p><p>That means fewer assumptions, smaller useful releases, and a clear line between what the software does and why it exists.</p></Reveal></div><div className="wrap principles"><div className="principle"><b>01</b><h3>Start with the constraint.</h3></div><div className="principle"><b>02</b><h3>Shape the experience and system together.</h3></div><div className="principle"><b>03</b><h3>Leave the next move visible.</h3></div></div></section><Cta /></> }

export function ServicesPage() { return <><PageIntro kicker="Services / The practice" title="Build what makes" accent="the work better.">From a focused internal workflow to a customer-facing product, strategy and implementation belong in the same conversation.</PageIntro><section className="section"><div className="wrap"><ServiceList /></div></section><section className="blue-section section"><div className="wrap split"><Reveal><div className="section-kicker">A connected practice</div><h2>Bring the friction.<br /><em>We will find the shape.</em></h2></Reveal><Reveal delay={.1}><p className="big-copy">You do not need to know whether the answer is an agent, an automation, an API, or a new interface. Start with the work that feels heavier than it should.</p></Reveal></div></section><Cta /></> }

export function ProcessPage() { return <><PageIntro kicker="Process / How we work" title="Good work starts" accent="with attention.">We keep the important decisions visible, the releases useful, and the path from first question to working system easy to understand.</PageIntro><section className="section"><div className="wrap"><ScrollStory items={processSteps.map(([number, title, text]) => ({ number, title, text }))} /></div></section><section className="dark-section section"><div className="wrap split"><Reveal><div className="section-kicker">The delivery posture</div><h2>Small releases.<br /><em>Real feedback.</em></h2></Reveal><Reveal delay={.1}><p className="big-copy">The first version is a learning instrument, not a monument. We make the unknowns visible early and leave the system easier to own.</p></Reveal></div></section><Cta /></> }

export function CapabilitiesPage() { return <><PageIntro kicker="Capabilities / Technical range" title="Meet the real" accent="stack underneath.">The right implementation respects what is already working, then makes the next layer more useful, accessible, and ready to evolve.</PageIntro><section className="section"><div className="wrap capability-grid">{capabilities.map(([number, title, text], i) => <Reveal key={number} delay={i * .05}><article className="capability-item"><span>{number}</span><h2>{title}</h2><p>{text}</p></article></Reveal>)}</div></section><section className="blue-section section"><div className="wrap split"><Reveal><div className="section-kicker">Integration principle</div><h2>Useful context.<br /><em>Explicit access.</em></h2></Reveal><Reveal delay={.1}><p className="big-copy">APIs, automations, and MCP integrations work best when permissions and context are deliberate. We build the connective layer that keeps AI helpful and accountable.</p></Reveal></div></section><Cta /></> }

function ContactForm() { const [status, setStatus] = useState(''); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const name = String(form.get('name') || '').trim(); const email = String(form.get('email') || '').trim(); const message = String(form.get('message') || '').trim(); if (!name || !email || !message) { setStatus('Please complete the fields before opening a draft.'); return } setStatus('Your email draft is ready to review. It has not been sent yet.'); window.location.href = buildContactMailto(name, email, message) }; return <Reveal delay={.1}><form className="contact-form" onSubmit={submit}><p className="form-note">This opens a pre-addressed email draft in your mail app. Nothing is sent until you review and send it.</p>{status && <p className="form-status" role="status">{status}</p>}<label htmlFor="name">Name<input id="name" name="name" required autoComplete="name" /></label><label htmlFor="email">Email<input id="email" name="email" type="email" required autoComplete="email" /></label><label htmlFor="message">What are you working through?<textarea id="message" name="message" rows={5} required /></label><button className="button button-blue" type="submit">Open email draft <ArrowUpRight aria-hidden="true" size={16} /></button></form></Reveal> }

export function ContactPage() { return <><PageIntro kicker="Contact / Start a project" title="Bring the" accent="real question.">Tell us what you are trying to improve, automate, or build. You do not need a polished brief to start a useful conversation.</PageIntro><section className="section"><div className="wrap contact-layout"><Reveal><div className="contact-aside"><div className="section-kicker">A good starting point</div><p className="big-copy">What is happening today? Where does the work slow down? What would a better version make possible?</p><p>Share the context you have. We will meet you there.</p><a href="mailto:hello@derricode.com" className="email-link">hello@derricode.com <ArrowUpRight aria-hidden="true" size={16} /></a></div></Reveal><ContactForm /></div></section></> }

export function NotFoundPage() { return <section className="page-intro wrap not-found"><Reveal><p className="eyebrow"><span className="pulse" />404 / Page not found</p><h1>Let us get you<br /><em>back on track.</em></h1><p className="lede">The page you requested does not exist. Return home or start a conversation about the thing you are trying to make.</p><Link className="button button-blue" href="/">Back to Derricode <ArrowUpRight aria-hidden="true" size={16} /></Link></Reveal></section> }
